# Dependencies
markdown:         kramdown 
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://pparkddo.github.io
baseurl:          

author:
  name:           'pparkddo'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/pparkddo

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-seo-tag
