# Dependencies
markdown: kramdown 
highlighter: rouge

# kramdown
kramdown:
  parse_block_html: true

# Permalinks
permalink: pretty

# Setup
title: Solved
tagline: Solve Problems
description: 문제 해결 방법과 이유를 정리한 <a href="http://github.com/pparkddo" target="_blank">pparkddo</a> 의 기술 블로그
url: https://pparkddo.github.io
baseurl: 

author:
  name: pparkddo

paginate: 5

# Custom vars
version: 1.0
image:
  path: /public/images

github:
  repo: https://github.com/pparkddo

# Seo Tag
locale: ko_KR

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
